Public_MVC/Controllers/ApartmentsController.cs
using System;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Public_MVC.Context;
using Public_MVC.Models;
using Public_MVC.Resources;
using Recaptcha.Web.Mvc;

namespace Public_MVC.Controllers
{
    public class ApartmentsController : Controller
    {
        private ApartmentsContext db = new ApartmentsContext();


        public ActionResult Index()
        {
            return View(db);
        }


        public ActionResult Details(int? id)
        {
            Apartment apartment = db.Apartments.Find(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (apartment == null)
            {
                return HttpNotFound();
            }
            return View(apartment);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult Filter(int? totalRooms, int? maxAdults, int? maxChildren, string city, string sortByPrice)
        {
            var apartments = db.Apartments.Where(a => a.IsDeleted == false).Where(a => a.ApartmentStatus.Name == "Slobodno");


            if (totalRooms.HasValue || maxAdults.HasValue || maxChildren.HasValue || !string.IsNullOrEmpty(city))
            {
                apartments = apartments.Where(a => (totalRooms == null || a.TotalRooms == totalRooms)
                                                            && (maxAdults == null || a.MaxAdults == maxAdults)
                                                            && (maxChildren == null || a.MaxChildren == maxChildren)
                                                            && (string.IsNullOrEmpty(city) || a.City.Name == city));
            }

            switch (sortByPrice)
            {
                case "default":
                    break;
                case "ascending":
                    apartments = apartments.OrderBy(a => a.Price);
                    break;
                case "descending":
                    apartments = apartments.OrderByDescending(a => a.Price);
                    break;
            }

            HttpCookie cityCookie = new HttpCookie("city");
            cityCookie.Value = city;
            HttpContext.Response.Cookies.Remove("city");
            HttpContext.Response.SetCookie(cityCookie);

            HttpCookie roomsCookie = new HttpCookie("rooms");
            roomsCookie.Value = totalRooms.ToString();
            HttpContext.Response.Cookies.Remove("rooms");
            HttpContext.Response.SetCookie(roomsCookie)
                ;
            HttpCookie adultsCookie = new HttpCookie("adults");
            adultsCookie.Value = maxAdults.ToString();
            HttpContext.Response.Cookies.Remove("adults");
            HttpContext.Response.SetCookie(adultsCookie);


            HttpCookie childrenCookie = new HttpCookie("children");
            childrenCookie.Value = maxChildren.ToString();
            HttpContext.Response.Cookies.Remove("children");
            HttpContext.Response.SetCookie(childrenCookie);

            HttpCookie sortCookie = new HttpCookie("sort");
            sortCookie.Value = sortByPrice;
            HttpContext.Response.Cookies.Remove("sort");
            HttpContext.Response.SetCookie(sortCookie);

            return PartialView("_FilteredApartments", apartments.ToList());
        }


        [HttpPost]
        public ActionResult LeaveReview(int apartmentId, string userName, ApartmentReview review)
        {
            
            try
            {
                var user = db.AspNetUsers.Where(u => u.Email == userName).FirstOrDefault();
                review.UserId = user.Id;
                review.CreatedAt = DateTime.Now;
                review.Guid = Guid.NewGuid();
                review.ApartmentId = apartmentId;
                db.ApartmentReviews.Add(review);
                db.SaveChanges();
                return Json(new { success = true, message = Resource.ajaxReviewMessageSuccess });

            }
            catch (Exception)
            {
                return Json(new { success = true, message = Resource.ajaxReviewMessageFailure });
            }
        }

        [HttpPost]
        public ActionResult ReserveApartment(string email, string phone, string address, int apartmentId, int? userId)
        {
            var apartment = db.Apartments.Find(apartmentId);

            var recaptchaHelper = this.GetRecaptchaVerificationHelper();

            if (recaptchaHelper.Response != null)
            {
                if (String.IsNullOrEmpty(recaptchaHelper.Response))
                {
                    return Json(new { success = false, message = Resource.captchaEmpty });
                }

                var recaptchaResult = recaptchaHelper.VerifyRecaptchaResponse();
                if (!recaptchaResult.Success)
                {
                    return Json(new { success = false, message = Resource.captchaWrong });
                }
            }
            

            

            try
            {
                ApartmentReservation reservation = new ApartmentReservation
                {
                    ApartmentId = apartmentId,
                    Guid = Guid.NewGuid(),
                    CreatedAt = DateTime.Now
                };

                if (userId != null)
                {
                    reservation.UserId = userId;
                }
                else
                {
                    reservation.UserName = email;
                    reservation.UserEmail = email;
                    reservation.UserAddress = address;
                    reservation.UserPhone = phone;
                }
                
                //Set to reserved
                apartment.ApartmentStatus = db.ApartmentStatus.FirstOrDefault(s => s.Id == 2);

                db.SaveChanges();


                return Json(new { success = true, message = Resource.ajaxReserveMessageSuccess });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = Resource.ajaxReserveMessageFailure });
            }
        }

        [HttpPost]
        public ActionResult ChangeLanguage(string culture)
        {
            
            Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(culture);

            HttpCookie cookie = new HttpCookie("culture", culture);
            cookie.Expires = DateTime.Now.AddYears(1);
            Response.Cookies.Add(cookie);

            return RedirectToAction("Index");
        }
    }
}

Public_MVC/Views/Shared/_Layout.cshtml
@using Public_MVC.Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RWA Apartments</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/MyCss/CardsAndDetails.css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet"
          href="~/Content/jquery.fancybox.css"
          type="text/css"
          media="screen" />
    <link href=" https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css " rel="stylesheet" />
    <style>
        body {
            background-image: linear-gradient(to bottom, #e9e9e9 0%, #fafafa 100%);
        }
    </style>

</head>
<body>
    <div class="container" style="display: flex; flex-direction: column; min-height: 100vh;">
        <main>
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Rwa", "Index", "Apartments", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink(Resource.apartments, "Index", "Apartments")</li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
            <div class="body-content" style="width: 100%;">
                @RenderBody()
            </div>
        </main>

        <footer class="pt-3 bg-dark" style="margin-top: 1.25rem;">
            <p class="text-center">&copy; @DateTime.Now.Year Leo Žarković</p>
            <p class="text-center">Algebra University College</p>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.fancybox.pack.js")
    @RenderSection("scripts", required: false)
    <script src=" https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.all.min.js "></script>


    <script>
        $(document).ready(function () {
            $(".fancy-photo").fancybox({
                cyclic: true,
                onUpdate: function () {
                    $(".fancybox-nav span").css({
                        visibility: "visible"
                    });
                    return;
                },
                afterClose: function () {
                    $(".fancybox-nav span").css({
                        visibility: "hidden"
                    });
                    return;
                }
            });
        });
    </script>
</body>
</html>